# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH

---
annotations:
  category: "Security"
  licenses: "AGPL-3.0-only"
apiVersion: "v2"
dependencies:
  - name: "common"
    version: "^2.x.x"
    repository: "oci://registry-1.docker.io/bitnamicharts"
  - name: "nats"
    version: "0.2.0"
    repository: "oci://gitregistry.knut.univention.de/univention/customers/dataport/upx/nats-helm/helm"
    condition: "nats.enabled"
description: "A Helm Chart that deploys the provisioning services"
keywords:
  - "provisioning"
name: "provisioning"
sources:
  - "https://git.knut.univention.de/univention/customers/dataport/upx/provisioning/-/tree/main/helm/provisioning?ref_type=heads"
type: "application"
version: "0.45.0"
...
