# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH

---
annotations:
  category: "Security"
  licenses: "AGPL-3.0-only"
apiVersion: "v2"
dependencies:
  - name: "common"
    version: "^2.x.x"
    repository: "oci://registry.souvap-univention.de/souvap/tooling/charts/bitnami-charts"
  - name: "nats"
    version: "^0.x.x"
    repository: "oci://registry.souvap-univention.de/souvap/tooling/charts/univention"
    condition: "nats.enabled"
description: "A Helm Chart that deploys the provisioning services"
keywords:
  - "provisioning"
name: "provisioning"
sources:
  - "https://git.knut.univention.de/univention/customers/dataport/upx/provisioning/-/tree/main/helm/provisioning?ref_type=heads"
type: "application"
version: "0.13.0"
...
