# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH
---
global:
  configMapUcr: "dummy-ucr-configmap-name"
  nats:
    auth:
      admin:
        existingSecret:
          name: "{{ .Release.Name }}-provisioning-nats-credentials"
      provisioningApi:
        existingSecret:
          name: "{{ .Release.Name }}-provisioning-api-credentials"
          keyMapping:
            provisioningApiPassword: NATS_PASSWORD
      prefill:
        existingSecret:
          name: "{{ .Release.Name }}-provisioning-prefill-credentials"
          keyMapping:
            prefillPassword: NATS_PASSWORD
      dispatcher:
        existingSecret:
          name: "{{ .Release.Name }}-provisioning-dispatcher-credentials"
          keyMapping:
            dispatcherPassword: NATS_PASSWORD
      udmTransformer:
        existingSecret:
          name: "{{ .Release.Name }}-provisioning-udm-transformer-credentials"
          keyMapping:
            udmTransformerPassword: NATS_PASSWORD
      udmListener:
        existingSecret:
          name: "{{ .Release.Name }}-provisioning-udm-listener-credentials"
          keyMapping:
            udmListenerPassword: NATS_PASSWORD

resources:
  dispatcher:
    limits:
      cpu: "1"
      memory: "1Gi"
    requests:
      cpu: "100m"
      memory: "32Mi"
  prefill:
    config:
      UDM_HOST: "udm-host"
    limits:
      cpu: "1"
      memory: "1Gi"
    requests:
      cpu: "100m"
      memory: "32Mi"
  api:
    limits:
      cpu: "1"
      memory: "1Gi"
    requests:
      cpu: "100m"
      memory: "32Mi"
  udmTransformer:
    limits:
      cpu: "1"
      memory: "1Gi"
    requests:
      cpu: "100m"
      memory: "32Mi"

ldap:
  auth:
    cnAdmin:
      password:
        # create: true
        name: "dummy-ldap-cn-admin-secret-name"
        key: "dummy-ldap-cn-admin-secret-key"
        # value: null

api:
  auth:
    admin:
      existingSecret:
        name: "provisioning-api-admin-secret-name"
        keyMapping:
          password: "provisioning-api-admin-secret-key"
    eventsUdm:
      existingSecret:
        name: "provisioning-api-events-udm-secret-name"
        keyMapping:
          password: "provisioning-api-events-udm-secret-key"
    prefill:
      existingSecret:
        name: "provisioning-api-prefill-secret-name"
        keyMapping:
          password: "provisioning-api-prefill-secret-key"

prefill:
  config:
    UDM_HOST: "udm-host"
udmTransformer:
  ldap:
    connection:
      host: "ldap-host"
      port: "1234"
    baseDn: "ldap-base-dn"
    auth:
      bindDn: "ldap-bind-dn"

registerConsumers:
  provisioningApiBaseUrl: "provisioning-base-url"
  createUsers:
    portalConsumer:
      username: "dummy-portal-consumer-username"
      # TODO: not yet supported
      # password: null
      existingSecret:
        name: "{{ .Release.Name }}-dummy-provisioning-portal-consumer-secret-name"
        keyMapping:
          password: "dummy-provisioning-portal-consumer-secret-key"
        # value: null
    selfserviceConsumer:
      username: "dummy-selfservice-consumer-username"
      # TODO: not yet supported
      # password: null
      existingSecret:
        name: "{{ .Release.Name }}-dummy-provisioning-selfservice-consumer-secret-name"
        keyMapping:
          password: "dummy-provisioning-selfservice-consumer-secret-key"
        # value: null
...
