# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH
---
resources:
  dispatcher:
    limits:
      cpu: "1"
      memory: "1Gi"
    requests:
      cpu: "100m"
      memory: "32Mi"
  prefill:
    config:
      UDM_HOST: "udm-host"
    limits:
      cpu: "1"
      memory: "1Gi"
    requests:
      cpu: "100m"
      memory: "32Mi"
  api:
    limits:
      cpu: "1"
      memory: "1Gi"
    requests:
      cpu: "100m"
      memory: "32Mi"
  udmTransformer:
    limits:
      cpu: "1"
      memory: "1Gi"
    requests:
      cpu: "100m"
      memory: "32Mi"

ldap:
  auth:
    cnAdmin:
      password:
        # create: true
        name: "dummy-ldap-cn-admin-secret-name"
        key: "dummy-ldap-cn-admin-secret-key"
        # value: null

prefill:
  config:
    UDM_HOST: "udm-host"
udmTransformer:
  ldap:
    connection:
      host: "ldap-host"
      port: "1234"
    baseDn: "ldap-base-dn"
    auth:
      bindDn: "ldap-bind-dn"
registerConsumers:
  provisioningApiBaseUrl: "provisioning-base-url"
...
