# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH
---
global:
  configMapUcr: "dummy-ucr-configmap-name"
  nats:
    auth:
      admin:
        existingSecret:
          name: nats-admin-account-secret-name
          keyMapping:
            adminPassword: nats-admin-account-secret-key
      provisioningApi:
        existingSecret:
          name: nats-provisioning-api-account-secret-name
          keyMapping:
            provisioningApiPassword: nats-provisioning-api-account-secret-key
      prefill:
        existingSecret:
          name: nats-prefill-account-secret-name
          keyMapping:
            prefillPassword: nats-prefill-account-secret-key
      dispatcher:
        existingSecret:
          name: nats-dispatcher-account-secret-name
          keyMapping:
            dispatcherPassword: nats-dispatcher-account-secret-key
      udmTransformer:
        existingSecret:
          name: nats-udm-transformer-account-secret-name
          keyMapping:
            udmTransformerPassword: nats-udm-transformer-account-secret-key
      udmListener:
        existingSecret:
          name: nats-udm-listener-account-secret-name
          keyMapping:
            udmListenerPassword: nats-udm-listener-account-secret-key

resources:
  dispatcher:
    limits:
      cpu: "1"
      memory: "1Gi"
    requests:
      cpu: "100m"
      memory: "32Mi"
  prefill:
    config:
      UDM_HOST: "udm-host"
    limits:
      cpu: "1"
      memory: "1Gi"
    requests:
      cpu: "100m"
      memory: "32Mi"
  api:
    limits:
      cpu: "1"
      memory: "1Gi"
    requests:
      cpu: "100m"
      memory: "32Mi"
  udmTransformer:
    limits:
      cpu: "1"
      memory: "1Gi"
    requests:
      cpu: "100m"
      memory: "32Mi"

ldap:
  auth:
    cnAdmin:
      password:
        # create: true
        name: "dummy-ldap-cn-admin-secret-name"
        key: "dummy-ldap-cn-admin-secret-key"
        # value: null

prefill:
  config:
    UDM_HOST: "udm-host"
udmTransformer:
  ldap:
    connection:
      host: "ldap-host"
      port: "1234"
    baseDn: "ldap-base-dn"
    auth:
      bindDn: "ldap-bind-dn"
registerConsumers:
  provisioningApiBaseUrl: "provisioning-base-url"
  auth:
    portalConsumer:
      password:
        # create: null
        name: "dummy-provisioning-portal-consumer-secret-name"
        key: "dummy-provisioning-portal-consumer-secret-key"
        # value: null
    selfserviceConsumer:
      password:
        # create: null
        name: "dummy-provisioning-selfservice-consumer-secret-name"
        key: "dummy-provisioning-selfservice-consumer-secret-key"
        # value: null
...
