---
include:
  - project: "univention/customers/dataport/upx/common-ci"
    ref: "v1.1.1"
    file:
      # TODO: Sphinx docs inherits a stage definition from upstream,
      # has to be included before our default stages to avoid trouble.
      - "jobs/sphinx-docs.yaml"
      - "defaults/stages.yaml"
      - "defaults/souvap-workflow.yaml"
      - "templates/souvap.yaml"
      - "jobs/lint-pre-commit.yaml"
      - "jobs/lint-commit-messages.yaml"
      - "jobs/semantic-release-env.yaml"
      - "jobs/container-build.yaml"
      - "jobs/package-and-publish-helm-charts.yaml"

lint-pre-commit:
  before_script:
    - helm repo add bitnami https://charts.bitnami.com/bitnami

container-build:
  parallel:
    matrix:
      - IMAGE_NAME: "provisioning-dispatch"
        TARGET: "final"
      - IMAGE_NAME: "provisioning-dispatch-test"
        TARGET: "test"
  variables:
    CI_REGISTRY_IMAGE: "$CI_REGISTRY_IMAGE/${IMAGE_NAME}"
    DIGEST_PREFIX: "digest-${IMAGE_NAME}"
    DOCKERFILE_PATH: "docker/dispatch/Dockerfile"
    KANIKO_ARGS: "--target ${TARGET}"

container-generate-sbom:
  parallel:
    matrix:
      - IMAGE_NAME:
          - "provisioning-dispatch"
          - "provisioning-dispatch-test"
  variables:
    CI_REGISTRY_IMAGE: "$CI_REGISTRY_IMAGE/${IMAGE_NAME}"
    DIGEST_PREFIX: "digest-${IMAGE_NAME}"
    SBOM_PREFIX: "sbom-${IMAGE_NAME}"

container-sign:
  parallel:
    matrix:
      - IMAGE_NAME:
          - "provisioning-dispatch"
          - "provisioning-dispatch-test"
  variables:
    CI_REGISTRY_IMAGE: "$CI_REGISTRY_IMAGE/${IMAGE_NAME}"
    DIGEST_PREFIX: "digest-${IMAGE_NAME}"
    SBOM_PREFIX: "sbom-${IMAGE_NAME}"

container-security-scan:
  parallel:
    matrix:
      - IMAGE_NAME:
          - "provisioning-dispatch"
          - "provisioning-dispatch-test"
  variables:
    CI_REGISTRY_IMAGE: "$CI_REGISTRY_IMAGE/${IMAGE_NAME}"
    DIGEST_PREFIX: "digest-${IMAGE_NAME}"
    CODEQUALITY_REPORT_PREFIX: "gl-code-quality-report-${IMAGE_NAME}"

test-provisioning-dispatch:
  stage: "test"
  image: "${CI_REGISTRY_IMAGE}/provisioning-dispatch-test:${RELEASE_VERSION}"
  script:
    - poetry config virtualenvs.in-project true
    - poetry install --with dev
    - poetry run pytest --cov --cov-report=term --cov-report=xml:coverage.xml --cov-branch
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

publish-images:
  extends: ".push-image-souvap"
  variables:
    SOUVAP_IMAGE_NAME: "provisioning-dispatch"
    BUILD_IMAGE_TAG: "$CI_REGISTRY_IMAGE/provisioning-dispatch:${RELEASE_VERSION}"

publish-helm-charts-souvap:
  extends: ".publish-helm-charts-souvap"
...
