---
include:
  - project: "univention/customers/dataport/upx/common-ci"
    ref: "v1.9.8"
    file:
      # TODO: Sphinx docs inherits a stage definition from upstream,
      # has to be included before our default stages to avoid trouble.
      - "jobs/sphinx-docs.yaml"
      - "defaults/stages.yaml"
      - "defaults/souvap-workflow.yaml"
      - "templates/souvap.yaml"
      - "jobs/lint-pre-commit.yaml"
      - "jobs/lint-commit-messages.yaml"
      - "jobs/semantic-release-env.yaml"
      - "jobs/container-build.yaml"
      - "jobs/package-and-publish-helm-charts.yaml"

lint-pre-commit:
  before_script:
    - helm repo add bitnami https://charts.bitnami.com/bitnami

.build-matrix: &build-matrix
  - IMAGE_NAME: "provisioning-dispatch"
    KANIKO_ARGS: "--target final"
  - IMAGE_NAME: "provisioning-dispatch-test"
    KANIKO_ARGS: "--target test"

.publish-matrix: &publish-matrix
  - IMAGE_NAME:
    - "provisioning-dispatch"

container-build:
  parallel:
    matrix: *build-matrix
  variables:
    KANIKO_BUILD_CONTEXT: "${CI_PROJECT_DIR}"
    DOCKERFILE_PATH: "docker/provisioning-dispatch/Dockerfile"

container-generate-sbom:
  parallel:
    matrix: *build-matrix

container-sign:
  parallel:
    matrix: *build-matrix

container-security-scan:
  parallel:
    matrix: *build-matrix

test-provisioning-dispatch:
  stage: "test"
  image: "${CI_REGISTRY_IMAGE}/provisioning-dispatch-test:${RELEASE_VERSION}"
  script:
    - poetry config virtualenvs.in-project true
    - poetry install --with dev
    - poetry run pytest --cov --cov-report=term --cov-report=xml:coverage.xml --cov-branch
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

publish-images:
  extends: ".push-image-souvap"
  parallel:
    matrix: *publish-matrix

publish-helm-charts-souvap:
  extends: ".publish-helm-charts-souvap"
...
