---

include:
  - project: "univention/customers/dataport/upx/common-ci"
    ref: "v1.12.0"
    file:
      # TODO: Sphinx docs inherits a stage definition from upstream,
      # has to be included before our default stages to avoid trouble.
      - "jobs/sphinx-docs.yaml"
      - "defaults/stages.yaml"
      - "defaults/souvap-workflow.yaml"
      - "jobs/lint-pre-commit.yaml"
      - "jobs/lint-commit-messages.yaml"
      - "jobs/semantic-release-env.yaml"
      - "jobs/container-build-souvap.yaml"
      - "jobs/package-and-publish-helm-charts-souvap.yaml"
  - project: "univention/dist/docker-services"
    ref: "master"
    file:
      - "dind.yml"

lint-pre-commit:
  before_script:
    - helm repo add bitnami https://charts.bitnami.com/bitnami
    - helm repo add nats https://nats-io.github.io/k8s/helm/charts/

.build-matrix: &build-matrix
  - IMAGE_NAME: "provisioning-dispatcher"
    KANIKO_ARGS: "--target final"
    DOCKERFILE_PATH: "docker/provisioning-dispatcher/Dockerfile"
  - IMAGE_NAME: "provisioning-dispatch-test"
    KANIKO_ARGS: "--target test"
    DOCKERFILE_PATH: "docker/provisioning-dispatcher/Dockerfile"
  - IMAGE_NAME: "udm-listener"
    KANIKO_ARGS: "--target final"
    DOCKERFILE_PATH: "docker/udm-listener/Dockerfile"

.publish-matrix: &publish-matrix
  - IMAGE_NAME:
    - "provisioning-dispatcher"
  - IMAGE_NAME:
    - "udm-listener"

container-build:
  parallel:
    matrix: *build-matrix
  variables:
    KANIKO_BUILD_CONTEXT: "${CI_PROJECT_DIR}"

container-generate-sbom:
  parallel:
    matrix: *build-matrix

container-sign:
  parallel:
    matrix: *build-matrix

container-security-scan:
  parallel:
    matrix: *build-matrix

test-integration:
  stage: "test"
  extends: .dind
  image: "${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/docker:24.0.7"
  before_script:
    # Allow that the Docker API version is negotiated between client and server
    - unset DOCKER_API_VERSION
    - export IMAGE_TAG=${RELEASE_VERSION}
    - echo -e "\e[0Ksection_start:`date +%s`:docker_debug[collapsed=true]\r\e[0KDocker version details"
    - echo $IMAGE_TAG
    - docker version
    - echo -e "\e[0Ksection_end:`date +%s`:docker_debug\r\e[0K"
    - echo -e "\e[0Ksection_start:`date +%s`:docker_compose_config[collapsed=true]\r\e[0KDocker Compose configuration"
    - docker compose config test
    - echo -e "\e[0Ksection_end:`date +%s`:docker_compose_config\r\e[0K"
    - docker compose up --no-build --quiet-pull --wait --wait-timeout 60 nats
  script:
    - docker compose run --quiet-pull --rm test poetry config virtualenvs.in-project true
    - docker compose run --quiet-pull --rm test poetry install --with dev
    - docker compose run --quiet-pull --rm test poetry run pytest tests/integration
  after_script:
    - docker compose down --volumes

# TODO: docker compose run nats ... somehow
test-provisioning-dispatch:
  stage: "test"
  image: "${CI_REGISTRY_IMAGE}/provisioning-dispatch-test:${RELEASE_VERSION}"
  script:
    - poetry config virtualenvs.in-project true
    - poetry install --with dev
    - poetry run pytest --ignore=tests/integration/ --cov --cov-report=term --cov-report=xml:coverage.xml --cov-branch
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

push-image-souvap:
  parallel:
    matrix: *publish-matrix

container-sign-souvap:
  parallel:
    matrix: *publish-matrix

...
