# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH

services:
  events-and-consumer-api:
    image: "gitregistry.knut.univention.de/univention/customers/dataport/upx/provisioning/provisioning-events-and-consumer-api:${IMAGE_TAG:-latest}"
    build:
      context: .
      dockerfile: docker/events-and-consumer-api/Dockerfile
      args:
        - UCS_BASE_IMAGE_TAG=latest
    container_name: "events-and-consumer-api-dev"
    restart: "on-failure"
    environment:
      LOG_LEVEL: "DEBUG"
      NATS_HOST: "nats"
      NATS_PORT: "4222"
      NATS_USER: "api"
      NATS_PASSWORD: "apipass"
      ADMIN_NATS_USER: "admin"
      ADMIN_NATS_PASSWORD: "nimda"
      UDM_HOST: "udm-rest-api"
      ADMIN_USERNAME: "admin"
      ADMIN_PASSWORD: "provisioning"
      PREFILL_USERNAME: "prefill"
      PREFILL_PASSWORD: "prefillpass"
      EVENTS_USERNAME_UDM: "udm"
      EVENTS_PASSWORD_UDM: "udmpass"
    depends_on:
      - "nats"
    ports:
      - "7777:7777"

  nats:
    image: "nats:latest"
    environment:
      jetstream: "enabled"
    ports:
      - "4222:4222" # Client connections
      - "6222:6222" # Route connections
      - "8222:8222" # HTTP monitoring port
    volumes:
      - ./nats.dev.conf:/etc/nats-config/nats.conf
      - type: tmpfs
        target: /var/run
    command: --jetstream -m 8222 -p 4222 -config /etc/nats-config/nats.conf


  dispatcher:
    image: "gitregistry.knut.univention.de/univention/customers/dataport/upx/provisioning/provisioning-dispatcher:${IMAGE_TAG:-latest}"
    build:
      context: .
      dockerfile: docker/dispatcher/Dockerfile
      args:
        - UCS_BASE_IMAGE_TAG=latest
    container_name: "provisioning-dispatcher"
    restart: "on-failure"
    environment:
      LOG_LEVEL: "DEBUG"
      NATS_HOST: "nats"
      NATS_PORT: "4222"
      NATS_USER: "dispatcher"
      NATS_PASSWORD: "dispatcherpass"
      INTERNAL_API_HOST: "events-and-consumer-api"
    depends_on:
      - "nats"
      - "events-and-consumer-api"

  udm-transformer:
    image: "gitregistry.knut.univention.de/univention/customers/dataport/upx/provisioning/provisioning-udm-transformer:${IMAGE_TAG:-latest}"
    build:
      context: .
      dockerfile: docker/udm-transformer/Dockerfile
      args:
        - UCS_BASE_IMAGE_TAG=latest
    container_name: "provisioning-udm-transformer"
    restart: "on-failure"
    environment:
      LOG_LEVEL: "DEBUG"
      NATS_HOST: "nats"
      NATS_PORT: "4222"
      NATS_USER: "udm-transformer"
      NATS_PASSWORD: "udm-transformerpass"

      INTERNAL_API_HOST: "events-and-consumer-api"
      EVENTS_USERNAME_UDM: "udm"
      EVENTS_PASSWORD_UDM: "udmpass"

      LDAP_HOST: "ldap-server"
      # LDAP_HOST: "localhost"
      LDAP_PORT: 389
      LDAP_TLS_MODE: "off"
      LDAP_BASE_DN: "dc=univention-organization,dc=intranet"
      LDAP_BIND_DN: "cn=admin,dc=univention-organization,dc=intranet"
      LDAP_BIND_PW: "univention"
    depends_on:
      - "nats"
      - "events-and-consumer-api"
    # network_mode: "host"

  prefill:
    image: "gitregistry.knut.univention.de/univention/customers/dataport/upx/provisioning/provisioning-prefill:${IMAGE_TAG:-latest}"
    build:
      context: .
      dockerfile: docker/prefill/Dockerfile
      args:
        - UCS_BASE_IMAGE_TAG=latest
    container_name: "provisioning-prefill"
    restart: "on-failure"
    environment:
      LOG_LEVEL: "DEBUG"
      NATS_HOST: "nats"
      NATS_PORT: "4222"
      INTERNAL_API_HOST: "events-and-consumer-api"
      NATS_USER: "prefill"
      NATS_PASSWORD: "prefillpass"
      UDM_HOST: "udm-rest-api"
      UDM_USERNAME: "cn=admin"
      UDM_PASSWORD: "univention"
      PREFILL_USERNAME: "prefill"
      PREFILL_PASSWORD: "prefillpass"
    depends_on:
      - "nats"
      - "events-and-consumer-api"

  udm-listener:
    image: "gitregistry.knut.univention.de/univention/customers/dataport/upx/provisioning/provisioning-udm-listener:${IMAGE_TAG:-latest}"
    build:
      context: .
      dockerfile: docker/udm-listener/Dockerfile
      args:
        - LISTENER_BASE_IMAGE_TAG=latest
        - UCS_BASE_IMAGE_TAG=latest
    container_name: "udm-listener"
    environment:
      NATS_HOST: "localhost"
      NATS_PORT: "4222"
      NATS_USER: "udmlistener"
      NATS_PASSWORD: "udmlistenerpass"
      LDAP_HOST: "localhost"
      LDAP_BASE_DN: "dc=univention-organization,dc=intranet"
      LDAP_HOST_DN: "cn=admin,dc=univention-organization,dc=intranet"
      NOTIFIER_SERVER: "localhost"
      DEBUG_LEVEL: "3"
      TLS_MODE: "off"
      LDAP_PASSWORD: "univention"
      LDAP_PASSWORD_FILE: "/var/secrets/ldap_secret"
      LDAP_PORT: 389
    network_mode: "host"
    depends_on:
      - "nats"
      - "ldap-server"
      - "ldap-notifier"

  ldap-notifier:
    platform: linux/amd64
    image: gitregistry.knut.univention.de/univention/customers/dataport/upx/container-ldap/ldap-notifier:latest
    depends_on:
      ldap-server:
        condition: service_started
    ports:
      - 6669:6669
    volumes:
      - ldap-shared-data:/var/lib/univention-ldap/:rw
      - ldap-shared-run:/var/run/slapd/:ro

  example-client:
    image: "gitregistry.knut.univention.de/univention/customers/dataport/upx/provisioning/provisioning-example-client:${IMAGE_TAG:-latest}"
    build:
      context: .
      dockerfile: docker/example-client/Dockerfile
      args:
        - UCS_BASE_IMAGE_TAG=latest
    container_name: example-client
    environment:
      PROVISIONING_API_USERNAME: "example-client"
      PROVISIONING_API_PASSWORD: "password"
      PROVISIONING_API_BASE_URL: "http://events-and-consumer-api:7777"
    restart: "on-failure"


  test:
    image: "gitregistry.knut.univention.de/univention/customers/dataport/upx/provisioning/test:${IMAGE_TAG:-latest}"
    build:
      context: .
      dockerfile: docker/test/Dockerfile
      args:
        - UCS_BASE_IMAGE_TAG=latest
    working_dir: /app
    profiles:
      - test
    platform: "linux/amd64"
    volumes:
      - "./tests:/app/tests"
      - "./src:/app/src"
      - "./pyproject.toml:/app/pyproject.toml"

  # Environment of the pre-commit linter.
  pre-commit:
    profiles:
      - test
    image: gitregistry.knut.univention.de/univention/customers/dataport/upx/container-pre-commit/upx-pre-commit:latest
    volumes:
      - type: bind
        source: .
        target: /code
      - type: volume
        # pre-commit installs dependencies, having them cached speeds things up
        # a lot.
        source: pre-commit-cache
        target: /cache

  # Environment to build the documentation
  docs:
    image: docker-registry.knut.univention.de/sphinx:latest
    working_dir: /src/docs
    volumes:
      - ".:/src"
    profiles:
      - docs

  ldap-server:
    platform: linux/amd64
    image: gitregistry.knut.univention.de/univention/customers/dataport/upx/container-ldap/ldap-server:latest
    container_name: "ldap-server"
    environment:
      DOMAIN_NAME: univention-organization.intranet
      LDAP_BASE_DN: dc=univention-organization,dc=intranet
      LDAP_CN_ADMIN_PW: "univention"
      TLS_MODE: "off"
    ports:
      - 389:389
      - 636:636
    volumes:
      - ldap-shared-data:/var/lib/univention-ldap/:rw
      - ldap-shared-run:/var/run/slapd/:rw
      - type: bind
        source: ./tests/base.conf
        target: /etc/univention/base.conf
        read_only: true

  ldap-admin:
    image: osixia/phpldapadmin:0.9.0
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "#PYTHON2BASH:[{'ldap-server':{'login':{'bind_id':'cn=admin,dc=univention-organization,dc=intranet'}}}]"
      PHPLDAPADMIN_HTTPS: "false"
    links:
      - ldap-server
    ports:
      - 8001:80

  udm-rest-api:
    image: gitregistry.knut.univention.de/univention/customers/dataport/upx/container-udm-rest/udm-rest-api:latest
    container_name: "udm-rest-api"
    platform: "linux/amd64"
    ports:
      - 9979:9979
    volumes:
      - type: bind
        source: ./tests/base.conf
        target: /etc/univention/base.conf
        read_only: true
    environment:
      DOMAINNAME: univention-organization.intranet
      HOSTNAME: localhost:9979
      LDAP_HOST: ldap-server
      LDAP_PORT: 389
      LDAP_BASE_DN: dc=univention-organization,dc=intranet
      LDAP_HOST_DN: cn=admin,dc=univention-organization,dc=intranet
      TLS_MODE: off
      MACHINE_SECRET: univention
      LDAP_CN_ADMIN_PW: univention

volumes:
  pre-commit-cache:
  ldap-shared-data:
  ldap-shared-run:
