# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH

services:
  app:
    build:
      context: .
      dockerfile: docker/events-and-consumer-api/Dockerfile
      args:
        - UCS_BASE_IMAGE_TAG=latest
    container_name: "events-and-consumer-api-dev"
    restart: "on-failure"
    environment:
      LOG_LEVEL: "DEBUG"
      NATS_HOST: "nats"
      UDM_HOST: "udm-rest-api"
      ADMIN_USERNAME: "admin"
      ADMIN_PASSWORD: "provisioning"
    depends_on:
      - "nats"
    ports:
      - "7777:7777"

  nats:
    image: "nats:latest"
    environment:
      jetstream: "enabled"
    ports:
      - "4222:4222" # Client connections
      - "6222:6222" # Route connections
      - "8222:8222" # HTTP monitoring port
    command: --jetstream -m 8222 -p 4222


  dispatcher:
    build:
      context: .
      dockerfile: docker/dispatcher/Dockerfile
      args:
        - UCS_BASE_IMAGE_TAG=latest
    container_name: "provisioning-dispatcher"
    restart: "on-failure"
    environment:
      LOG_LEVEL: "DEBUG"
      NATS_HOST: "nats"
      CONSUMER_EVENT_HOST: "app"
    depends_on:
      - "nats"
      - "app"

  prefill:
    build:
      context: .
      dockerfile: docker/prefill/Dockerfile
      args:
        - UCS_BASE_IMAGE_TAG=latest
    container_name: "provisioning-prefill"
    restart: "on-failure"
    environment:
      LOG_LEVEL: "DEBUG"
      NATS_HOST: "nats"
      CONSUMER_EVENT_HOST: "app"
      UDM_HOST: "udm-rest-api"
    depends_on:
      - "nats"
      - "app"

  udm-listener:
    build:
      context: .
      dockerfile: docker/udm-listener/Dockerfile
      args:
        - LISTENER_BASE_IMAGE_TAG=latest
        - UCS_BASE_IMAGE_TAG=latest
    container_name: "udm-listener"
    environment:
      LDAP_HOST: "localhost"
      LDAP_BASE_DN: "dc=univention-organization,dc=intranet"
      LDAP_HOST_DN: "cn=admin,dc=univention-organization,dc=intranet"
      NOTIFIER_SERVER: "localhost"
      DEBUG_LEVEL: "4"
      TLS_MODE: "off"
      LDAP_PASSWORD: "univention"
      LDAP_PASSWORD_FILE: "/var/secrets/ldap_secret"
    network_mode: "host"

  ldap-notifier:
    platform: linux/amd64
    image: gitregistry.knut.univention.de/univention/customers/dataport/upx/container-ldap/ldap-notifier:latest
    depends_on:
      ldap-server:
        condition: service_started
    ports:
      - 6669:6669
    volumes:
      - ldap-shared-data:/var/lib/univention-ldap/:rw
      - ldap-shared-run:/var/run/slapd/:ro

  test:
    profiles:
      - test
    platform: "linux/amd64"
    environment:
      nats_host: nats
    image: gitregistry.knut.univention.de/univention/customers/dataport/upx/provisioning/events-and-consumer-api-test:${IMAGE_TAG:-latest}
    build:
      context: docker/events-and-consumer-api-test
    volumes:
      - type: bind
        source: .
        target: /app/

  # Environment of the pre-commit linter.
  pre-commit:
    profiles:
      - test
    image: gitregistry.knut.univention.de/univention/customers/dataport/upx/container-pre-commit/upx-pre-commit:latest
    volumes:
      - type: bind
        source: .
        target: /code
      - type: volume
        # pre-commit installs dependencies, having them cached speeds things up
        # a lot.
        source: pre-commit-cache
        target: /cache

  # Environment to build the documentation
  docs:
    image: docker-registry.knut.univention.de/sphinx:latest
    working_dir: /src/docs
    volumes:
      - ".:/src"
    profiles:
      - docs

  ldap-server:
    platform: linux/amd64
    image: gitregistry.knut.univention.de/univention/customers/dataport/upx/container-ldap/ldap-server:latest
    container_name: "ldap-server"
    environment:
      DOMAIN_NAME: univention-organization.intranet
      LDAP_BASE_DN: dc=univention-organization,dc=intranet
      LDAP_CN_ADMIN_PW: "univention"
      TLS_MODE: "off"
    ports:
      - 389:389
      - 636:636
    volumes:
      - ldap-shared-data:/var/lib/univention-ldap/:rw
      - ldap-shared-run:/var/run/slapd/:rw
      - type: bind
        source: ./tests/base.conf
        target: /etc/univention/base.conf
        read_only: true

  ldap-admin:
    image: osixia/phpldapadmin:0.9.0
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "#PYTHON2BASH:[{'ldap-server':{'login':{'bind_id':'cn=admin,dc=univention-organization,dc=intranet'}}}]"
      PHPLDAPADMIN_HTTPS: "false"
    links:
      - ldap-server
    ports:
      - 8001:80

  udm-rest-api:
    image: gitregistry.knut.univention.de/univention/customers/dataport/upx/container-udm-rest/udm-rest-api:latest
    container_name: "udm-rest-api"
    platform: "linux/amd64"
    ports:
      - 9979:9979
    volumes:
      - type: bind
        source: ./tests/base.conf
        target: /etc/univention/base.conf
        read_only: true
    environment:
      DOMAINNAME: univention-organization.intranet
      HOSTNAME: localhost:9979
      LDAP_HOST: localhost
      LDAP_PORT: 389
      LDAP_BASE_DN: dc=univention-organization,dc=intranet
      LDAP_HOST_DN: cn=admin,dc=univention-organization,dc=intranet
      TLS_MODE: off
      MACHINE_SECRET: univention
      LDAP_CN_ADMIN_PW: univention

volumes:
  pre-commit-cache:
  ldap-shared-data:
  ldap-shared-run: