services:
  app:
    profiles:
      - dev
    build:
      context: .
      dockerfile: docker/provisioning-dispatch/Dockerfile
    container_name: "provisioning-dispatcher-dev"
    restart: "on-failure"
    environment:
      LOG_LEVEL: "DEBUG"
    depends_on:
      - "nats"
    ports:
      - "7777:7777"

  nats:
    image: "nats:latest"
    environment:
      jetstream: "enabled"
    ports:
      - "4222:4222" # Client connections
      - "6222:6222" # Route connections
      - "8222:8222" # HTTP monitoring port
    command: --jetstream -m 8222 -p 4222

  dispatcher:
    build:
      context: .
      dockerfile: docker/dispatcher-service/Dockerfile
    container_name: "dispatcher-service"
    restart: "on-failure"
    environment:
      LOG_LEVEL: "INFO"
      NATS_HOST: "nats"
    depends_on:
      - "nats"

#    # TODO: this is probably only useful temporarily, since the udm-listener also should be part of the Tilt stack,
#  # but then maybe for integration testing ...
#  udm-listener:
#    # LDAP server and notifier need to be there
#    image: gitregistry.knut.univention.de/univention/customers/dataport/upx/provisioning-api/udm-listener:${IMAGE_TAG:-latest}
#    environment:
#      # this config relies on running ldap server and notifier that have ports forwarded
#      LDAP_HOST: "localhost"
#      LDAP_BASE_DN: "dc=univention-organization,dc=intranet"
#      LDAP_HOST_DN: "cn=admin,dc=univention-organization,dc=intranet"
#      NOTIFIER_SERVER: "localhost"
#      LDAP_PORT: "3089"
#      DEBUG_LEVEL: "4"
#      # Whether to start encryption and validate certificates.
#      # Chose from "off", "unvalidated" and "secure".
#      TLS_MODE: "off"
#      LDAP_PASSWORD: "univention"
#      LDAP_PASSWORD_FILE: "/var/secrets/ldap_secret"
#    network_mode: "host"

  test:
    profiles:
      - test
    platform: "linux/amd64"
    environment:
      nats_host: nats
    image: gitregistry.knut.univention.de/univention/customers/dataport/upx/provisioning-api/provisioning-dispatch-test:${IMAGE_TAG:-latest}
    build:
      context: docker/provisioning-dispatch-test
    volumes:
      - type: bind
        source: .
        target: /app/

  # Environment of the pre-commit linter.
  pre-commit:
    profiles:
      - test
    image: gitregistry.knut.univention.de/univention/customers/dataport/upx/container-pre-commit/upx-pre-commit:latest
    volumes:
      - type: bind
        source: .
        target: /code
      - type: volume
        # pre-commit installs dependencies, having them cached speeds things up
        # a lot.
        source: pre-commit-cache
        target: /cache

  # Environment to build the documentation
  docs:
    image: docker-registry.knut.univention.de/sphinx:latest
    working_dir: /src/docs
    volumes:
      - ".:/src"
    profiles:
      - docs

  openldap:
    image: osixia/openldap:latest
    container_name: openldap
    hostname: openldap
    ports:
      - "389:389"
      - "636:636"
    environment:
      - LDAP_ORGANISATION=univention-organization
      - LDAP_DOMAIN=univention-organization.intranet
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=admin_pass
      - LDAP_CONFIG_PASSWORD=config_pass
      - "LDAP_BASE_DN=dc=univention-organization,dc=intranet"
      - LDAP_TLS_CRT_FILENAME=server.crt
      - LDAP_TLS_KEY_FILENAME=server.key
      - LDAP_TLS_CA_CRT_FILENAME=univention-organization.ca.crt
      - LDAP_READONLY_USER=true
      - LDAP_READONLY_USER_USERNAME=user-ro
      - LDAP_READONLY_USER_PASSWORD=ro-pass
    networks:
      - openldap

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    hostname: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "80:80"
    depends_on:
      - openldap
    networks:
      - openldap


volumes:
  pre-commit-cache:

networks:
  openldap:
    driver: bridge