[tool.poetry]
name = "provisioning-dispatch"
version = "0.1.0"
description = "Univention Management Stack - Provisioning Dispatch Service"
authors = [
  "Univention GmbH <packages@univention.de>",
]
license = "GNU Affero General Public License v3"
readme = "README.md"
packages = [
    { include = "example-client", from = "src" },
    { include = "core", from = "src" },
    { include = "dispatcher", from = "src" },
]

[tool.poetry.dependencies]
fastapi = "^0.103.1"
pydantic = "^2.3.0"
pydantic-settings = "^2.0.3"
python = "^3.9"
pyyaml = "^6.0.1"
uvicorn = "^0.23.2"
redis = "^5.0.0"
aiohttp = "^3.8.5"
websockets = "^11.0.3"

[tool.poetry.scripts]
dev = "dispatcher:start_dev"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
httpx = "^0.24.0"
pytest = "^7.4.2"
fakeredis = "2.19.0"
pytest-cov = "4.1"

[tool.ruff]
line-length = 120

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
