[tool.poetry]
name = "provisioning"
version = "0.1.0"
description = "Univention Management Stack - Provisioning Service"
authors = [
  "Univention GmbH <packages@univention.de>",
]
license = "GNU Affero General Public License v3"
readme = "README.md"
packages = [{ include = "server", from = "src" }, ]

[tool.poetry.dependencies]
fastapi = "^0.103.1"
pydantic = "^2.3.0"
pydantic-settings = "^2.0.3"
python = "^3.7"
pyyaml = "^6.0.1"
uvicorn = "^0.21.1"
aiohttp = "^3.8.5"
trio = "^0.22.2"
daemoniker = "^0.2.3"
requests = "^2.31.0"
ldap3 = "^2.9.1"
passlib = "^1.7.4"
bcrypt = "4.0.1"
nats-py = "^2.7.0"
msgpack = "1.0.*"

[tool.poetry.scripts]
dev = "src.server.core.app:start_dev"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
httpx = "^0.24.0"
pytest = "^7.4.2"
pytest-cov = "4.1"
pytest-timeout = "2.3.1"
udm-rest-api-client = "^0.0.2"

[[tool.poetry.source]]
name = "PyPI"
priority = "primary"

[tool.ruff]
target-version = "py311"
line-length = 120

[tool.ruff.lint]
extend-select = ["I"]  # activate isort

[tool.pytest.ini_options]
asyncio_mode = "auto"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
