[tool.poetry]
name = "provisioning"
version = "0.1.0"
description = "Univention Management Stack - Provisioning Service"
authors = [
  "Univention GmbH <packages@univention.de>",
]
license = "GNU Affero General Public License v3"
readme = "README.md"
packages = [
    { include = "example-client", from = "src" },
    { include = "shared", from = "src" },
    { include = "consumer", from = "src" },
    { include = "prefill", from = "src" },
]

[tool.poetry.dependencies]
fastapi = "^0.103.1"
pydantic = "^2.3.0"
pydantic-settings = "^2.0.3"
python = "^3.7"
pyyaml = "^6.0.1"
uvicorn = "^0.21.1"
aiohttp = "^3.8.5"
websockets = "^11.0.3"
nats-py = "^2.6.0"
trio = "^0.22.2"
daemoniker = "^0.2.3"
requests = "^2.31.0"
ldap3 = "^2.9.1"

[tool.poetry.scripts]
dev = "consumer:start_dev"
client = "example-client.main:run"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
httpx = "^0.24.0"
pytest = "^7.4.2"
pytest-cov = "4.1"

[tool.ruff]
line-length = 120

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
