# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH

---
# Default values for the UMS provisioning udm-listener.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


## Global values
affinity: {}
environment: {}
fullnameOverride: ""
nameOverride: ""
nodeSelector: {}
podAnnotations: {}
podSecurityContext: {}
replicaCount: 1
securityContext: {}
tolerations: []


image:
  registry: "gitregistry.knut.univention.de"
  repository: "univention/customers/dataport/upx/provisioning/udm-listener"
  imagePullPolicy: "Always"
  tag: "latest"


# -- Configuration of the UDM Listener that is notified on LDAP changes
config:
  environment: "production"
  # -- CA root certificate, base64-encoded. Optional; will be written to "caCertFile" if set.
  caCert: "/var/secrets/ca_cert"
  # -- Where to search for the CA Certificate file.
  # caCertFile: "/var/secrets/ca_cert"
  caCertFile: ""
  debugLevel: "4"
  ldapBaseDn: null
  # -- LDAP password for `cn=admin`. Will be written to "ldapPasswordFile" if set.
  ldapPassword: ""
  # -- The path to the "ldapPasswordFile" docker secret or a plain file
  ldapPasswordFile: "/var/secrets/ldap_secret"
  ldapHost: "ldap-server"
  ldapHostDn: null
  # -- Will add a mapping from "ldapHost" to "ldapHostIp" into "/etc/hosts" if set
  ldapHostIp: null
  ldapPort: "389"
  # -- Defaults to "ldapHost" if not set.
  notifierServer: "ldap-notifier"
  # -- Whether to start encryption and validate certificates.
  # Chose from "off", "unvalidated" and "secure".
  tlsMode: "off"


## Container deployment probes
probes:
  liveness:
    enabled: true
    initialDelaySeconds: 120
    timeoutSeconds: 3
    periodSeconds: 30
    failureThreshold: 3
    successThreshold: 1

  readiness:
    enabled: true
    initialDelaySeconds: 30
    timeoutSeconds: 3
    periodSeconds: 15
    failureThreshold: 30
    successThreshold: 1


serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

## Deployment resources
resources:
  requests:
    memory: "512Mi"
  limits:
    memory: "4Gi"

...
