# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH

---
{{ include "common.configMap" (dict "top" . "overrides" "provisioning-api.configMap") }}
{{- define "provisioning-api.configMap" }}
{{- with .top }}
data:
  LOG_LEVEL: "{{ .Values.config.logLevel }}"
  DEBUG: "{{ .Values.config.debug }}"
  ROOT_PATH: "{{ .Values.config.rootPath }}"
  CORS_ALL: "{{ .Values.config.corsAll }}"
  {{- if .Values.nats.bundled }}
  NATS_HOST: "{{ include "common.names.dependency.fullname" (dict "chartName" "nats" "chartValues" .Values.nats "context" $.top) }}"
  NATS_PORT: "4222"
  {{- else }}
  NATS_HOST: {{ required "The parameter \"nats.connection.host\" is required." .Values.nats.connection.host | quote }}
  NATS_PORT: {{ required "The parameter \"nats.connection.port\" is required." .Values.nats.connection.port | quote }}
  {{- end }}
{{- end }}
{{- end }}
...
