# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH

---

apiVersion: "v2"
type: "application"
name: "udm-listener"
description: "A Helm chart for the Univention Portal Provisioning API"
home: "https://www.univention.de/"

# Chart version
# Apply Semantic Versioning (https://semver.org/)
version: "0.1.0"

# Portal Version
appVersion: "1.16.0"

dependencies:
  - name: "common"
    version: "^2.x.x"
    repository: "oci://registry-1.docker.io/bitnamicharts"

...
