# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH

---
# The global properties are used to configure multiple charts at once.
global:
  # -- Indicates wether this chart is part of a Nubus deployment.
  nubusDeployment: false


# Default values for the UMS provisioning udm-listener.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


## Global values
affinity: {}
environment: {}
fullnameOverride: ""
nameOverride: ""
nodeSelector: {}
podAnnotations: {}
podSecurityContext: {}
replicaCount: 1
securityContext: {}
tolerations: []
mountSecrets: true

image:
  registry: ""
  repository: "nubus-dev/images/provisioning-udm-listener"
  imagePullPolicy: "Always"
  tag: "latest"


# -- Configuration of the UDM Listener that is notified on LDAP changes
config:
  # -- CA root certificate, base64-encoded. Optional; will be written to "caCertFile" if set.
  caCert: ""
  # -- Where to search for the CA Certificate file.
  # caCertFile: "/var/secrets/ca_cert"
  caCertFile: ""
  debugLevel: "4"
  ldapBaseDn: null
  # -- LDAP password for `cn=admin`. Will be written to "ldapPasswordFile" if set.
  ldapPassword: ""
  # -- The path to the "ldapPasswordFile" docker secret or a plain file
  ldapPasswordFile: "/var/secrets/ldap_secret"
  ldapHost: ""
  ldapHostDn: null
  # -- Will add a mapping from "ldapHost" to "ldapHostIp" into "/etc/hosts" if set
  ldapHostIp: null
  ldapPort: "389"
  # -- NATS: host (required if nats.bundled == false)
  natsHost: null
  # -- NATS: port (required if nats.bundled == false)
  natsPort: "4222"
  # -- NATS: user name
  natsUser: "udmlistener"
  # -- NATS: password
  natsPassword: "udmlistenerpass"
  # -- Messages-API Hostname
  internalApiHost: "provisioning-api"
  # -- Messages-API Port
  eventsUsernameUdm: "udm"
  eventsPasswordUdm: "udmpass"
  internalApiPort: "80"
  # -- Defaults to "ldapHost" if not set.
  notifierServer: "ldap-notifier"
  # -- Whether to start encryption and validate certificates.
  # Chose from "off", "unvalidated" and "secure".
  tlsMode: "off"
  # -- Path to mount the secrets to.
  secretMountPath: "/var/secrets"
  provisioningApi:
    auth:
      credentialSecret:
        name: ""
        userNameKey: "EVENTS_USERNAME_UDM"
        passwordKey: "EVENTS_PASSWORD_UDM"

## Container deployment probes
probes:
  liveness:
    enabled: true
    initialDelaySeconds: 10
    timeoutSeconds: 3
    periodSeconds: 10
    failureThreshold: 30
    successThreshold: 1

  readiness:
    enabled: true
    initialDelaySeconds: 10
    timeoutSeconds: 3
    periodSeconds: 10
    failureThreshold: 3
    successThreshold: 1


serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

## Deployment resources
resources: {}
  # requests:
  #   memory: "512Mi"
  # limits:
  #   memory: "4Gi"

ldap:
  tlsSecret:
    name: ""
    caCertKey: "ca.crt"
  credentialSecret:
    name: ""
    ldapPasswordKey: "ldap.secret"
    machinePasswordKey: "machine.secret"

nats:
  bundled: true
  auth:
    credentialSecret:
      name: ""
      key: "NATS_PASSWORD"
...
