# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH

---
{{ include "common.configMap" (dict "top" . "overrides" "udm-listener.configMap") }}
{{- define "udm-listener.configMap" }}
{{- with .top }}
data:
  CA_CERT: "{{ .Values.config.caCert }}"
  CA_CERT_FILE: "{{ .Values.config.caCertFile }}"
  DEBUG_LEVEL: "{{ .Values.config.debugLevel }}"
  LDAP_BASE_DN: {{ include "udm-listener.ldapBaseDn" . | quote }}
  LDAP_PASSWORD: "{{ .Values.config.ldapPassword }}"
  LDAP_PASSWORD_FILE: "{{ .Values.config.ldapPasswordFile }}"
  LDAP_HOST: {{ include "udm-listener.ldap.connection.host" . | quote }}
  LDAP_HOST_DN: {{ include "udm-listener.ldapAdminDn" . | quote }}
  LDAP_PORT: {{ include "udm-listener.ldap.connection.port" . | quote }}
  NATS_HOST: {{ include "udm-listener.nats.connection.host" . | quote }}
  NATS_PORT: {{ include "udm-listener.nats.connection.port" . | quote }}
  INTERNAL_API_HOST: {{ include "udm-listener.provisioningApi.connection.host" . | quote }}
  INTERNAL_API_PORT: {{ include "udm-listener.provisioningApi.connection.port" . | quote }}
  NOTIFIER_SERVER: {{ include "udm-listener.ldapNotifier.connection.host" . | quote }}
  TLS_MODE: "{{ .Values.config.tlsMode }}"
{{ end }}
{{ end }}
...
