---
{{ include "common.configMap" (dict "top" . "overrides" "provisioning-api.configMap") }}

{{- define "provisioning-api.configMap" }}
{{- with .top }}
data:
  LOG_LEVEL: "{{ .Values.provisioningApi.logLevel }}"
  DEBUG: "{{ .Values.provisioningApi.debug }}"
  ROOT_PATH: "{{ .Values.provisioningApi.rootPath }}"
  CORS_ALL: "{{ .Values.provisioningApi.corsAll }}"
  REDIS_HOST: "{{ .Values.provisioningApi.redisHost }}"
  REDIS_PORT: "{{ .Values.provisioningApi.redisPort }}"
  UDM_URL: {{ required "The parameter \"provisioningApi.udmUrl\" is required." .Values.provisioningApi.udmUrl | quote }}
  UDM_USERNAME: {{ required "The parameter \"provisioningApi.udmUsername\" is required." .Values.provisioningApi.udmUsername | quote }}
  UDM_PASSWORD: {{ required "The parameter \"provisioningApi.udmPassword\" is required." .Values.provisioningApi.udmPassword | quote }}
{{- end }}
{{- end }}
...
