---
{{ include "common.configMap" (dict "top" . "overrides" "provisioning-api.configMap") }}

{{- define "provisioning-api.configMap" }}
{{- with .top }}
data:
  LOG_LEVEL: "{{ .Values.provisioningApi.logLevel }}"
  DEBUG: "{{ .Values.provisioningApi.debug }}"
  ROOT_PATH: "{{ .Values.provisioningApi.rootPath }}"
  CORS_ALL: "{{ .Values.provisioningApi.corsAll }}"
  {{- if .Values.nats.bundled }}
  NATS_HOST: "{{ include "common.names.dependency.fullname" (dict "chartName" "nats" "chartValues" .Values.nats "context" $.top) }}"
  NATS_PORT: "{{ .Values.provisioningApi.natsPort }}"
  {{- else }}
  NATS_HOST: {{ required "The parameter \"nats.connection.host\" is required." .Values.nats.connection.host | quote }}
  NATS_PORT: {{ required "The parameter \"nats.connection.port\" is required." .Values.nats.connection.port | quote }}
  {{- end }}
  UDM_URL: {{ required "The parameter \"provisioningApi.udmUrl\" is required." .Values.provisioningApi.udmUrl | quote }}
  UDM_USERNAME: {{ required "The parameter \"provisioningApi.udmUsername\" is required." .Values.provisioningApi.udmUsername | quote }}
  UDM_PASSWORD: {{ required "The parameter \"provisioningApi.udmPassword\" is required." .Values.provisioningApi.udmPassword | quote }}
{{- end }}
{{- end }}
...
