# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH
---
imagePullSecrets:
  - "kyverno-test"
replicaCount: 42

nats:
  config:
    cluster:
      replicas: 42

global:
  imageRegistry: "my_private_registry.domain.tld"
  imagePullSecrets:
    - "kyverno-test"
  imagePullPolicy: "kyverno"
persistence:
  storageClassNames:
    RWX: "kyverno-test"
    RWO: "kyverno-test"
  size:
    clamav: "42Gi"
...
