# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH
---
kind: "ConfigMap"
apiVersion: "v1"
metadata:
  name: {{ printf "%s-common" (include "common.names.fullname" .) }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.additionalLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.additionalLabels "context" . ) | nindent 4 }}
    {{- end }}
  {{- if .Values.additionalAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.additionalAnnotations "context" . ) | nindent 4 }}
  {{- end }}
data:
  {{- if .Values.nats.bundled }}
  NATS_HOST: {{ printf "%s-nats" (include "common.names.fullname" .) }}
  NATS_PORT: "4222"
  {{- else }}
  NATS_HOST: {{ required ".Values.nats.connection.host is required." .Values.nats.connection.host | quote }}
  NATS_PORT: {{ required ".Values.nats.connection.port is required." .Values.nats.connection.port | quote }}
  {{- end }}
  {{- if .Values.nats.connection.token }}
  NATS_CLIENTAUTH_TOKEN: {{ .Values.nats.connection.token | quote }}
  {{- end }}
  {{- if .Values.nats.connection.tls.enabled }}
  NATS_TLS_KEY_FILE: {{ required ".Values.nats.connection.tls.keyFile is required." .Values.nats.connection.tls.keyFile | quote }}
  NATS_TLS_CERT_FILE: {{ required ".Values.nats.connection.tls.certFile is required." .Values.nats.connection.tls.certFile | quote }}
  NATS_TLS_CA_FILE: {{ required ".Values.nats.connection.tls.caFile is required." .Values.nats.tls.caFile | quote }}
  {{- end }}
...
---
kind: "ConfigMap"
apiVersion: "v1"
metadata:
  name: {{ printf "%s-api" (include "common.names.fullname" .) }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.additionalLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.additionalLabels "context" . ) | nindent 4 }}
    {{- end }}
  {{- if .Values.additionalAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.additionalAnnotations "context" . ) | nindent 4 }}
  {{- end }}
data:
  LOG_LEVEL: "{{ .Values.api.config.logLevel }}"
  DEBUG: "{{ .Values.api.config.debug }}"
  ROOT_PATH: "{{ .Values.api.config.rootPath }}"
  CORS_ALL: "{{ .Values.api.config.corsAll }}"
...

