# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH

---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ printf "%s-register-consumers" (include "common.names.fullname" .) }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
      {{- $commonLabels := include "common.labels.standard" . | fromYaml }}
      {{- $uiLabels := dict "app.kubernetes.io/name" (printf "%s-registerConsumers" (include "common.names.fullname" .)) }}
      {{- $mergedLabels := merge $uiLabels $commonLabels}}
      {{- toYaml $mergedLabels | nindent 4 }}
    {{- if .Values.registerConsumers.additionalLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.registerConsumers.additionalLabels "context" . ) | nindent 4 }}
    {{- end }}
  {{- if .Values.registerConsumers.additionalAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.registerConsumers.additionalAnnotations "context" . ) | nindent 4 }}
  {{- end }}
spec:
  template:
    metadata:
      annotations:
        checksum/configmap: {{ include (print .Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- if .Values.registerConsumers.podAnnotations }}
        {{- include "common.tplvalues.render" (dict "value" .Values.registerConsumers.podAnnotations "context" .) | nindent 8 }}
        {{- end }}
      labels:
        {{- $commonLabels := include "common.labels.standard" . | fromYaml }}
        {{- $uiLabels := dict "app.kubernetes.io/name" (printf "%s-register-consumers" (include "common.names.fullname" .)) }}
        {{- $mergedLabels := merge $uiLabels $commonLabels}}
        {{- toYaml $mergedLabels | nindent 8 }}
    spec:
      {{- if or .Values.imagePullSecrets .Values.global.imagePullSecrets  }}
      imagePullSecrets:
        {{- range .Values.global.imagePullSecrets }}
        - name: "{{ . }}"
        {{- end }}
        {{- range .Values.imagePullSecrets }}
        - name: "{{ . }}"
        {{- end }}
      {{- end }}
      restartPolicy: Never
      volumes:
        - name: consumer-secrets
        {{- if (include "provisioning-register-consumers.jsonSecretName" .) }}
          secret:
            secretName: {{ include "provisioning-register-consumers.jsonSecretName" . | quote }}
        {{- end }}
        - name: "scripts-volume"
          configMap:
            name: {{ printf "%s-wait-for-api" (include "common.names.fullname" .) }}
            defaultMode: 0555
        - name: wait-for-data-loader
          configMap:
            name: {{ printf "%s-register-consumers" (include "common.names.fullname" .) }}
      initContainers:
        - name: wait-for-provisioning-api
          image: "{{ coalesce .Values.registerConsumers.image.registry .Values.global.imageRegistry }}/{{ .Values.registerConsumers.image.repository }}:{{ .Values.registerConsumers.image.tag }}"
          imagePullPolicy: {{ coalesce .Values.registerConsumers.image.imagePullPolicy .Values.global.imagePullPolicy | quote }}
          envFrom:
            - configMapRef:
                name: {{ printf "%s-register-consumers" (include "common.names.fullname" .) }}
          command: ["/bin/bash", "-c", "/scripts/wait-for-api.sh ${PROVISIONING_API_BASE_URL}"]
          {{- if .Values.resources.registerConsumers }}
          resources: {{- include "common.tplvalues.render" (dict "value" .Values.resources.registerConsumers "context" .) | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: scripts-volume
              mountPath: /scripts
        - name: wait-for-data-loader
          command: ["/bin/bash", "/scripts/wait-for-data-loader.sh"]
          image: "{{ coalesce .Values.registerConsumers.image.registry .Values.global.imageRegistry }}/{{ .Values.registerConsumers.image.repository }}:{{ .Values.registerConsumers.image.tag }}"
          imagePullPolicy: {{ coalesce .Values.registerConsumers.image.imagePullPolicy .Values.global.imagePullPolicy | quote }}
          envFrom:
            - configMapRef:
                name: {{ printf "%s-register-consumers" (include "common.names.fullname" .) }}
          env:
            - name: UDM_USERNAME
              value: "cn=admin"
            - name: UDM_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "provisioning.ldap.auth.cnAdmin.name" . }}
                  key: {{ include "provisioning.ldap.auth.cnAdmin.key" . }}
          volumeMounts:
            - name: wait-for-data-loader
              mountPath: /scripts
          {{- if .Values.resources.registerConsumers }}
          resources: {{- include "common.tplvalues.render" (dict "value" .Values.resources.registerConsumers "context" .) | nindent 12 }}
          {{- end }}
      containers:
        - name: consumer-registration
          image: "{{ coalesce .Values.registerConsumers.image.registry .Values.global.imageRegistry }}/{{ .Values.registerConsumers.image.repository }}:{{ .Values.registerConsumers.image.tag }}"
          imagePullPolicy: {{ coalesce .Values.registerConsumers.image.imagePullPolicy .Values.global.imagePullPolicy | quote }}
          volumeMounts:
            - name: consumer-secrets
              mountPath: "/secrets"
          envFrom:
            - configMapRef:
                name: {{ printf "%s-register-consumers" (include "common.names.fullname" .) }}
          env:
            - name: ADMIN_USERNAME
              value: "admin"
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "provisioning.provisioningApi.auth.admin.name" . }}
                  key: {{ include "provisioning.provisioningApi.auth.admin.key" . }}
          command:
            - "/bin/sh"
            - "-c"
          args:
            - |
              for file in /secrets/*; do
                filename=$(basename "${file}" .json)
                response=$(set +x; curl -s -o response.txt -w "%{http_code}" -u "${ADMIN_USERNAME}":"${ADMIN_PASSWORD}" \
                -H 'Content-Type: application/json' \
                -d @"${file}" "${PROVISIONING_API_BASE_URL}")

                if [ "${response}" -eq 201 ]; then
                  echo "Successful registration of the consumer: "${filename}""
                elif [ "${response}" -eq 200 ]; then
                  echo "Consumer with the name '"${filename}"' is already registered with the same parameters"
                else
                  echo "Failed to register the consumer: "${filename}"
              Response code: "${response}"
              Response body: $(cat response.txt)"
                  exit 1
                fi
                echo ------------------------------------
              done
          {{- if .Values.resources.registerConsumers }}
          resources: {{- include "common.tplvalues.render" (dict "value" .Values.resources.registerConsumers "context" .) | nindent 12 }}
          {{- end }}
