---

apiVersion: "v2"
type: "application"
name: "provisioning-api"
description: "A Helm chart for the Univention Portal Provisioning API"
home: "https://www.univention.de/"

# Chart version
# Apply Semantic Versioning (https://semver.org/)
version: "0.1.0"

# Portal Version
appVersion: "1.16.0"

dependencies:
  - name: "common"
    alias: "ums-common"
    repository: "oci://gitregistry.knut.univention.de/univention/customers/dataport/upx/common-helm/helm"
    version: "^0.2.0"
  - name: "redis"
    repository: "https://charts.bitnami.com/bitnami"
    version: "^18.0.0"
    condition: "redis"

...
