---

# Dummy values for running the Helm linter on the provisioning-api.
# Run it like this: helm lint -f values.yaml -f linter_values.yaml .


## Application-specific
provisioningApi:
  logLevel: "INFO"
  debug: true
  rootPath: ""
  corsAll: false
  natsHost: "localhost"
  natsPort: 4222


## Kubernetes ingress
ingress:
  enabled: false
  host: "portal.example.develop.souvap-univention.de"


## Istio based
istio:
  enabled: true
  host: "portal.example.develop.souvap-univention.de"


## Docker image
image:
  tag: "branch-feature-example"


## Container deployment probes
probes:
  liveness:
    enabled: false

  readiness:
    enabled: false

...
