# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH

---
# Default values for the UMS provisioning api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


## Global values
affinity: {}
environment: {}
fullnameOverride: "provisioning-api"
nameOverride: ""
nodeSelector: {}
podAnnotations: {}
podSecurityContext: {}
replicaCount: 1
securityContext: {}
tolerations: []


image:
  registry: "gitregistry.knut.univention.de"
  repository: "univention/customers/dataport/upx/provisioning/provisioning-dispatch"
  imagePullPolicy: "Always"
  tag: "latest"

# -- Application specific
config:
  # -- Python log level
  logLevel: "INFO"
  # -- FastAPI: debug mode
  debug: true
  # -- FastAPI: webserver root path
  rootPath: "/univention/provisioning-api"
  # -- FastAPI: disable CORS checks
  corsAll: false
  # -- NATS: host (required if nats.bundled == false)
  natsHost: "localhost"
  # -- NATS: port (required if nats.bundled == false)
  natsPort: 4222


## Kubernetes ingress
ingress:
  # -- Set this to `true` in order to enable the installation on Ingress related objects.
  enabled: true
  ingressClassName: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^/univention/provisioning-api(/.*)$ $1 break;
    nginx.org/location-snippets: |
      rewrite ^/univention/provisioning-api(/.*)$ $1 break;
    nginx.org/mergeable-ingress-type: "minion"
  # -- The hostname. This parameter has to be supplied. Example `portal.example`.
  host: null
  paths:
    - pathType: "Prefix"
      path: "/univention/provisioning-api/"
  tls:
    enabled: true
    secretName: ""

## Istio support
istio:
  # -- Set this to `true` in order to enable the installation on Istio related objects.
  enabled: false
  # -- The hostname. This parameter has to be supplied. Example `portal.example`.
  host: null
  virtualService:
    enabled: true
    annotations:
  gateway:
    enabled: false
    annotations:
    selectorIstio: "ingressgateway"
    externalGatewayName: "swp-istio-gateway"
    tls:
      enabled: true
      httpsRedirect: true
      secretName: ""


## Container deployment probes
probes:
  liveness:
    enabled: true
    initialDelaySeconds: 120
    timeoutSeconds: 3
    periodSeconds: 30
    failureThreshold: 3
    successThreshold: 1

  readiness:
    enabled: true
    initialDelaySeconds: 30
    timeoutSeconds: 3
    periodSeconds: 15
    failureThreshold: 30
    successThreshold: 1


## Deployment resources
resources:
  requests:
    memory: "512Mi"
  limits:
    memory: "4Gi"

## Kubernetes Service
service:
  enabled: true
  type: "ClusterIP"
  ports:
    http:
      containerPort: 7777
      port: 80
      protocol: "TCP"

  sessionAffinity:
    enabled: false
    timeoutSeconds: 10800


nats:
  bundled: true
...
