# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH

---
{{ include "common.secret" (dict "top" . "overrides" "udm-listener.secret") }}

{{- define "udm-listener.secret" }}
{{- with .top }}
data:
  ldap_secret: {{ .Values.config.ldapPassword | b64enc | quote }}
  ca_cert: {{ .Values.config.caCert | quote }}
{{- end }}
{{- end }}
...
